# Use root/example as user/password credentials
services:
  mongo:
    container_name: mongodb-server
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_SERVER: mongodb-server

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      - API_URL=doc/swagger.yaml
